"""Curated starting board — companies hiring engineers in India.

Kept out of companies.py so the domain logic stays readable: this is data, and
it will grow.

Every `ats` token here was verified against the live public board before being
committed, which is not a formality — six plausible-looking tokens turned out
to belong to somebody else entirely ("tcs" is a UK care provider, "slice" is a
US pizza company, "linkedin" is a Greenhouse test board). A wrong token doesn't
error, it silently lists the wrong company's jobs, so an unverified guess is
worse here than an honest `none`.

Companies with `none` still earn their place: the board is a shortlist to work
from, and the assistant can search the web for those (see ai.py). Add a token
whenever you find one — `discover.py` picks it up with no other change.
"""

from __future__ import annotations

from typing import Any


def _c(
    name: str,
    category: str,
    tier: str,
    locations: str,
    careers_url: str,
    *,
    summary: str = "",
    aliases: tuple[str, ...] = (),
    ats: tuple[str, str] | None = None,
    focus: str = "swe",
    stack: str = "",
    hq: str | None = None,
) -> dict[str, Any]:
    provider, token = ats if ats else ("none", None)
    return {
        "name": name,
        "aliases": list(aliases),
        "category": category,
        "tier": tier,
        "hq": hq,
        "locations": [c.strip() for c in locations.split(",") if c.strip()],
        "careers_url": careers_url,
        "ats_provider": provider,
        "ats_token": token,
        "focus": [f.strip() for f in focus.split(",") if f.strip()],
        "tech_stack": [t.strip() for t in stack.split(",") if t.strip()],
        "org_summary": summary,
        "status": "researching",
    }


SEED: list[dict[str, Any]] = [
    # ----------------------------------------------------------------------
    # Global majors with large India engineering centres. None of them expose
    # a public board API — they all run their own or Workday — so these are
    # careers-page links and WebSearch territory.
    # ----------------------------------------------------------------------
    _c("Google", "mnc", "faang", "Bengaluru, Hyderabad, Pune, Gurugram",
       "https://www.google.com/about/careers/applications/jobs/results/?location=India",
       summary="Search, Cloud, Android; the largest non-US engineering presence is in India.",
       aliases=("Google India", "Alphabet"), focus="swe,ai_ml,infra", hq="Mountain View, US"),
    _c("Microsoft", "mnc", "faang", "Bengaluru, Hyderabad, Noida",
       "https://jobs.careers.microsoft.com/global/en/search?lc=India",
       summary="Azure, Office, and the India Development Centre in Hyderabad.",
       aliases=("Microsoft IDC",), focus="swe,ai_ml,infra", hq="Redmond, US"),
    _c("Amazon", "mnc", "faang", "Bengaluru, Hyderabad, Chennai, Delhi",
       "https://www.amazon.jobs/en/locations/india",
       summary="Retail, AWS and Alexa engineering across four Indian cities.",
       aliases=("Amazon India", "AWS"), focus="swe,backend,infra", hq="Seattle, US"),
    _c("Apple", "mnc", "faang", "Hyderabad, Bengaluru",
       "https://jobs.apple.com/en-in/search?location=india-INDC",
       summary="Maps, Siri and silicon work out of Hyderabad and Bengaluru.",
       focus="swe,ai_ml", hq="Cupertino, US"),
    _c("Meta", "mnc", "faang", "Bengaluru, Gurugram",
       "https://www.metacareers.com/jobs?offices[0]=Bangalore",
       summary="Ads and infrastructure engineering; smaller India footprint than peers.",
       aliases=("Facebook",), focus="swe,ai_ml", hq="Menlo Park, US"),
    _c("Netflix", "mnc", "faang", "Mumbai",
       "https://explore.jobs.netflix.net/careers", summary="Streaming; small India presence.",
       focus="swe", hq="Los Gatos, US"),
    _c("Adobe", "mnc", "tier1", "Noida, Bengaluru",
       "https://careers.adobe.com/us/en/search-results?keywords=india",
       summary="Creative Cloud and Experience Cloud; Noida is a major R&D site.",
       focus="swe,ai_ml", hq="San Jose, US"),
    _c("Salesforce", "mnc", "tier1", "Hyderabad, Bengaluru",
       "https://careers.salesforce.com/en/jobs/?location=India",
       summary="CRM and platform engineering; Hyderabad is the main India hub.",
       focus="swe,backend", hq="San Francisco, US"),
    _c("Uber", "mnc", "tier1", "Bengaluru, Hyderabad",
       "https://www.uber.com/us/en/careers/list/?location=IND",
       summary="Rides and Eats platform engineering from Bengaluru and Hyderabad.",
       focus="swe,backend,data", hq="San Francisco, US"),
    _c("Atlassian", "mnc", "tier1", "Bengaluru",
       "https://www.atlassian.com/company/careers/all-jobs?location=India",
       summary="Jira and Confluence; Bengaluru site opened as a full product centre.",
       focus="swe,fullstack", hq="Sydney, AU"),
    _c("LinkedIn", "mnc", "tier1", "Bengaluru",
       "https://www.linkedin.com/jobs/linkedin-jobs/?location=India",
       summary="Professional network; Bengaluru does full product engineering.",
       focus="swe,data", hq="Sunnyvale, US"),
    _c("Nvidia", "mnc", "tier1", "Bengaluru, Pune, Hyderabad",
       "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
       summary="GPUs, CUDA and AI systems; large India silicon and software teams.",
       focus="ai_ml,infra,swe", hq="Santa Clara, US"),
    _c("Qualcomm", "mnc", "tier1", "Hyderabad, Bengaluru, Chennai, Noida",
       "https://careers.qualcomm.com/careers?location=India",
       summary="Mobile silicon and modem software; one of the largest India R&D bases.",
       focus="swe,infra", hq="San Diego, US"),
    _c("Oracle", "mnc", "tier2", "Bengaluru, Hyderabad, Noida",
       "https://careers.oracle.com/jobs", summary="OCI cloud and database engineering.",
       focus="swe,backend", hq="Austin, US"),
    _c("SAP", "mnc", "tier2", "Bengaluru, Gurugram", "https://jobs.sap.com/search/?q=india",
       summary="Enterprise software; SAP Labs Bengaluru is its biggest lab outside Germany.",
       aliases=("SAP Labs",), focus="swe,backend", hq="Walldorf, DE"),
    _c("Cisco", "mnc", "tier2", "Bengaluru, Chennai", "https://jobs.cisco.com/jobs/SearchJobs/india",
       summary="Networking hardware and software; Bengaluru is a principal site.",
       focus="swe,infra", hq="San Jose, US"),
    _c("Intel", "mnc", "tier2", "Bengaluru, Hyderabad", "https://jobs.intel.com/en/search-jobs/India",
       summary="Silicon design and systems software.", focus="swe,infra", hq="Santa Clara, US"),
    _c("IBM", "mnc", "tier2", "Bengaluru, Pune, Hyderabad, Kochi",
       "https://www.ibm.com/careers/search?field_keyword_05[0]=India",
       summary="Hybrid cloud, watsonx and consulting.", focus="swe,ai_ml", hq="Armonk, US"),
    _c("Walmart Global Tech India", "mnc", "tier1", "Bengaluru, Chennai",
       "https://careers.walmart.com/technology",
       summary="Retail platform engineering at scale; a common Flipkart-adjacent destination.",
       aliases=("Walmart Labs", "Walmart"), focus="swe,data,backend", hq="Bentonville, US"),
    _c("Goldman Sachs", "mnc", "tier1", "Bengaluru, Hyderabad",
       "https://www.goldmansachs.com/careers/students/programs/india",
       summary="Engineering division; Bengaluru is its largest office outside New York.",
       focus="swe,quant,data", hq="New York, US"),
    _c("JPMorgan Chase", "mnc", "tier2", "Mumbai, Bengaluru, Hyderabad",
       "https://careers.jpmorgan.com/global/en/students/programs/india",
       summary="Banking technology across three large India centres.",
       aliases=("JP Morgan",), focus="swe,data", hq="New York, US"),
    _c("Morgan Stanley", "mnc", "tier1", "Bengaluru, Mumbai",
       "https://www.morganstanley.com/careers/career-opportunities-search",
       summary="Institutional securities technology; strong India engineering bench.",
       focus="swe,quant", hq="New York, US"),
    _c("Visa", "mnc", "tier2", "Bengaluru", "https://corporate.visa.com/en/jobs/",
       summary="Payments infrastructure; Bengaluru technology centre.",
       focus="swe,backend", hq="Foster City, US"),
    _c("Mastercard", "mnc", "tier2", "Pune, Gurugram", "https://careers.mastercard.com/us/en/search-results",
       summary="Payments and data services; Pune is the main India tech centre.",
       focus="swe,data", hq="Purchase, US"),
    _c("PayPal", "mnc", "tier2", "Chennai, Bengaluru, Hyderabad",
       "https://careers.pypl.com/search-results", summary="Payments platform engineering.",
       focus="swe,backend", hq="San Jose, US"),
    _c("ServiceNow", "mnc", "tier1", "Hyderabad, Bengaluru",
       "https://careers.servicenow.com/careers/", summary="Enterprise workflow platform.",
       focus="swe,fullstack", hq="Santa Clara, US"),
    _c("Expedia Group", "mnc", "tier2", "Gurugram", "https://careers.expediagroup.com/jobs/",
       summary="Travel marketplace engineering.", focus="swe,data", hq="Seattle, US"),
    _c("Samsung R&D India", "mnc", "tier2", "Bengaluru, Noida, Delhi",
       "https://www.samsung.com/in/aboutsamsung/careers/",
       summary="Device software and on-device AI; SRI-B is a large Bengaluru lab.",
       aliases=("Samsung", "SRI-B"), focus="swe,ai_ml,mobile", hq="Seoul, KR"),
    _c("Sprinklr", "mnc", "tier2", "Gurugram, Bengaluru", "https://careers.sprinklr.com/",
       summary="Customer experience management; large Gurugram engineering team.",
       focus="swe,fullstack", hq="New York, US"),

    # ----------------------------------------------------------------------
    # Global product companies with a public board and real India hiring.
    # ----------------------------------------------------------------------
    _c("Databricks", "product", "tier1", "Bengaluru", "https://www.databricks.com/company/careers",
       summary="Lakehouse platform; Bengaluru R&D centre opened 2023 and is scaling fast.",
       ats=("greenhouse", "databricks"), focus="swe,data,ai_ml", stack="Scala,Spark,Kubernetes"),
    _c("Snowflake", "product", "tier1", "Pune, Bengaluru", "https://careers.snowflake.com/us/en",
       summary="Cloud data warehouse; Pune is the India engineering site.",
       ats=("ashby", "snowflake"), focus="swe,data,infra", stack="C++,Java,AWS"),
    _c("Stripe", "product", "tier1", "Bengaluru", "https://stripe.com/jobs/search",
       summary="Payments APIs; Bengaluru hub covers infrastructure and product.",
       ats=("greenhouse", "stripe"), focus="swe,backend", stack="Ruby,Go,Scala"),
    _c("MongoDB", "product", "tier1", "Gurugram, Bengaluru", "https://www.mongodb.com/careers",
       summary="Document database; India teams work on Atlas and the core server.",
       ats=("greenhouse", "mongodb"), focus="swe,backend,infra", stack="C++,Go,Kubernetes"),
    _c("Confluent", "product", "tier1", "Bengaluru", "https://careers.confluent.io/",
       summary="Managed Kafka and stream processing.",
       ats=("ashby", "confluent"), focus="swe,backend,data", stack="Java,Kafka,Go"),
    _c("Datadog", "product", "tier1", "Bengaluru", "https://careers.datadoghq.com/",
       summary="Observability platform; India office opened recently.",
       ats=("greenhouse", "datadog"), focus="swe,infra,data", stack="Go,Python,Kubernetes"),
    _c("Cloudflare", "product", "tier1", "Bengaluru", "https://www.cloudflare.com/careers/jobs/",
       summary="Edge network, CDN and zero-trust security.",
       ats=("greenhouse", "cloudflare"), focus="swe,infra,backend", stack="Go,Rust,Workers"),
    _c("Elastic", "product", "tier1", "Bengaluru, Remote", "https://jobs.elastic.co/jobs",
       summary="Elasticsearch and observability; distributed-first company.",
       ats=("greenhouse", "elastic"), focus="swe,data,infra", stack="Java,Go,Elasticsearch"),
    _c("GitLab", "product", "tier1", "Remote India", "https://about.gitlab.com/jobs/",
       summary="DevOps platform; fully remote, hires in India.",
       ats=("greenhouse", "gitlab"), focus="swe,fullstack,infra", stack="Ruby,Go,Vue"),
    _c("Okta", "product", "tier1", "Bengaluru", "https://www.okta.com/company/careers/",
       summary="Identity and access management.",
       ats=("greenhouse", "okta"), focus="swe,backend", stack="Java,Kotlin,AWS"),
    _c("Twilio", "product", "tier1", "Bengaluru", "https://www.twilio.com/en-us/company/jobs",
       summary="Communications APIs; Bengaluru engineering centre.",
       ats=("greenhouse", "twilio"), focus="swe,backend", stack="Java,Go,AWS"),
    _c("Zscaler", "product", "tier1", "Bengaluru, Mohali", "https://www.zscaler.com/careers",
       summary="Cloud security; one of the larger US-product India engineering teams.",
       ats=("greenhouse", "zscaler"), focus="swe,infra,backend", stack="Go,C++,Kubernetes"),
    _c("Rubrik", "product", "tier1", "Bengaluru, Pune", "https://www.rubrik.com/company/careers",
       summary="Data security and backup; Bengaluru is a major engineering site.",
       ats=("greenhouse", "rubrik"), focus="swe,infra,backend", stack="Go,C++,Distributed systems"),
    _c("Netskope", "product", "tier1", "Bengaluru", "https://www.netskope.com/company/careers",
       summary="Cloud security service edge; large Bengaluru team.",
       ats=("greenhouse", "netskope"), focus="swe,infra", stack="Go,Python,Kubernetes"),
    _c("Coinbase", "product", "tier1", "Remote India", "https://www.coinbase.com/careers",
       summary="Crypto exchange; remote-first with India hiring.",
       ats=("greenhouse", "coinbase"), focus="swe,backend", stack="Go,TypeScript"),
    _c("Airbnb", "product", "tier1", "Bengaluru, Remote", "https://careers.airbnb.com/",
       summary="Travel marketplace; limited but real India hiring.",
       ats=("greenhouse", "airbnb"), focus="swe,data", stack="Java,React"),
    _c("Roblox", "product", "tier1", "Remote", "https://careers.roblox.com/jobs",
       summary="Gaming platform; occasional India-eligible remote roles.",
       ats=("greenhouse", "roblox"), focus="swe,infra", stack="C++,Lua"),
    _c("OpenAI", "product", "tier1", "Bengaluru", "https://openai.com/careers/search/",
       summary="Frontier AI lab; announced a New Delhi office and is starting India hiring.",
       ats=("ashby", "openai"), focus="ai_ml,swe,infra", stack="Python,PyTorch"),
    _c("Perplexity AI", "startup", "tier1", "Remote", "https://www.perplexity.ai/careers",
       summary="AI answer engine; small team, occasional remote roles.",
       ats=("ashby", "perplexity"), focus="ai_ml,swe", stack="Python,TypeScript"),
    _c("Scale AI", "product", "tier1", "Remote", "https://scale.com/careers",
       summary="Data labelling and evaluation for frontier models.",
       ats=("greenhouse", "scaleai"), focus="ai_ml,swe,data", stack="Python,TypeScript"),
    _c("Vercel", "product", "tier1", "Remote", "https://vercel.com/careers",
       summary="Frontend cloud and Next.js.",
       ats=("greenhouse", "vercel"), focus="swe,frontend,infra", stack="TypeScript,Next.js,Rust"),
    _c("Sentry", "product", "tier2", "Remote", "https://sentry.io/careers/",
       summary="Error monitoring and tracing.",
       ats=("ashby", "sentry"), focus="swe,backend", stack="Python,TypeScript,Rust"),
    _c("Grafana Labs", "product", "tier1", "Remote India", "https://grafana.com/about/careers/",
       summary="Observability dashboards, Loki and Mimir; remote-first.",
       ats=("greenhouse", "grafanalabs"), focus="swe,infra", stack="Go,TypeScript"),
    _c("Fivetran", "product", "tier2", "Bengaluru", "https://www.fivetran.com/careers",
       summary="Managed ELT data pipelines; Bengaluru engineering office.",
       ats=("greenhouse", "fivetran"), focus="swe,data,backend", stack="Java,Kotlin,Scala"),
    _c("Harness", "product", "tier1", "Bengaluru", "https://www.harness.io/company/careers",
       summary="CI/CD and software delivery platform; Bengaluru is its largest engineering site.",
       ats=("greenhouse", "harnessinc"), focus="swe,infra,backend", stack="Java,Go,Kubernetes"),
    _c("Asana", "product", "tier2", "Bengaluru", "https://asana.com/jobs",
       summary="Work management; Bengaluru office.",
       ats=("greenhouse", "asana"), focus="swe,fullstack", stack="Python,TypeScript"),
    _c("Braze", "product", "tier2", "Bengaluru", "https://www.braze.com/company/careers",
       summary="Customer engagement platform.",
       ats=("greenhouse", "braze"), focus="swe,backend,data", stack="Ruby,Java,Kafka"),
    _c("Amplitude", "product", "tier2", "Remote", "https://amplitude.com/careers",
       summary="Product analytics.",
       ats=("greenhouse", "amplitude"), focus="swe,data", stack="Java,TypeScript"),
    _c("Commvault", "product", "tier2", "Bengaluru, Hyderabad", "https://www.commvault.com/careers",
       summary="Data protection and recovery; sizeable India engineering.",
       ats=("greenhouse", "commvault"), focus="swe,infra", stack="C++,Java"),
    _c("Sumo Logic", "product", "tier2", "Noida", "https://www.sumologic.com/careers/",
       summary="Log analytics and SIEM; Noida engineering centre.",
       ats=("greenhouse", "sumologic"), focus="swe,data,infra", stack="Scala,Kubernetes"),
    _c("Saviynt", "product", "tier2", "Bengaluru", "https://saviynt.com/careers",
       summary="Identity governance; Bengaluru is the main engineering site.",
       ats=("lever", "saviynt"), focus="swe,backend", stack="Java,Spring,AWS"),
    _c("Gainsight", "product", "tier2", "Hyderabad", "https://www.gainsight.com/company/careers/",
       summary="Customer success platform; Hyderabad engineering centre.",
       ats=("ashby", "gainsight"), focus="swe,fullstack", stack="Java,Angular"),
    _c("Zenoti", "product", "tier2", "Hyderabad, Bengaluru", "https://www.zenoti.com/careers",
       summary="Spa and salon SaaS; Hyderabad-built unicorn.",
       ats=("greenhouse", "zenoti"), focus="swe,fullstack", stack="C#,.NET,React"),
    _c("HighRadius", "product", "tier2", "Hyderabad, Bhubaneswar",
       "https://www.highradius.com/careers/",
       summary="Autonomous finance SaaS; hires heavily from Indian campuses.",
       ats=("greenhouse", "highradius"), focus="swe,ai_ml,fullstack", stack="Java,Angular,Python"),
    _c("Druva", "product", "tier2", "Pune, Bengaluru", "https://www.druva.com/about/careers",
       summary="SaaS data protection; founded in Pune, now US-headquartered.",
       ats=("greenhouse", "druva"), focus="swe,infra,backend", stack="Python,Go,AWS"),
    _c("Aera Technology", "product", "tier2", "Pune, Bengaluru", "https://www.aeratechnology.com/careers",
       summary="Decision intelligence for supply chains.",
       ats=("lever", "aeratechnology"), focus="swe,ai_ml,data", stack="Python,Java"),
    _c("Skyflow", "startup", "growth", "Bengaluru", "https://www.skyflow.com/careers",
       summary="Data privacy vault API.",
       ats=("ashby", "skyflow"), focus="swe,backend", stack="Go,Java"),
    _c("Turing", "product", "growth", "Remote India", "https://www.turing.com/jobs",
       summary="Remote engineering marketplace and AI training data.",
       ats=("greenhouse", "turing"), focus="swe,ai_ml", stack="Python,React"),

    # ----------------------------------------------------------------------
    # Indian product companies and unicorns.
    # ----------------------------------------------------------------------
    _c("Flipkart", "product", "tier1", "Bengaluru", "https://www.flipkartcareers.com/",
       summary="India's largest home-grown e-commerce platform, owned by Walmart.",
       focus="swe,backend,data", stack="Java,Kafka,Kubernetes"),
    _c("Swiggy", "product", "tier1", "Bengaluru", "https://careers.swiggy.com/",
       summary="Food delivery and quick commerce; Instamart is the growth engine.",
       aliases=("Bundl Technologies",), focus="swe,backend,data", stack="Java,Go,Kafka"),
    _c("Zomato", "product", "tier1", "Gurugram, Bengaluru", "https://www.zomato.com/careers",
       summary="Food delivery and Blinkit quick commerce; parent renamed Eternal.",
       aliases=("Eternal", "Blinkit"), ats=("lever", "eternal"),
       focus="swe,backend,data", stack="Go,Java,Kafka"),
    _c("Meesho", "product", "tier1", "Bengaluru", "https://www.meesho.io/jobs",
       summary="Zero-commission social commerce for price-sensitive India.",
       ats=("lever", "meesho"), focus="swe,backend,data", stack="Java,Python,Kafka"),
    _c("Razorpay", "product", "tier1", "Bengaluru", "https://razorpay.com/jobs/",
       summary="Payment gateway and neobanking for Indian businesses.",
       aliases=("Razorpay Software",), ats=("greenhouse", "razorpaysoftwareprivatelimited"),
       focus="swe,backend,fullstack", stack="Go,Java,React"),
    _c("PhonePe", "product", "tier1", "Bengaluru", "https://www.phonepe.com/careers/",
       summary="UPI payments at national scale; the largest UPI app by volume.",
       ats=("greenhouse", "phonepe"), focus="swe,backend,infra", stack="Java,Kafka,Aerospike"),
    _c("CRED", "product", "tier1", "Bengaluru", "https://careers.cred.club/",
       summary="Credit-card rewards and premium fintech.",
       aliases=("Dreamplug Technologies",), ats=("lever", "cred"),
       focus="swe,backend,mobile", stack="Kotlin,Java,Scala"),
    _c("Paytm", "product", "tier2", "Noida, Bengaluru", "https://jobs.paytm.com/",
       summary="Payments, commerce and financial services.",
       aliases=("One97 Communications",), ats=("lever", "paytm"),
       focus="swe,backend,data", stack="Java,Spring,Kafka"),
    _c("Groww", "product", "tier1", "Bengaluru", "https://groww.in/careers",
       summary="Retail investing and broking; one of India's largest brokers by users.",
       aliases=("Nextbillion Technology",), ats=("greenhouse", "groww"),
       focus="swe,backend,mobile", stack="Java,Kotlin,React"),
    _c("Zerodha", "product", "tier1", "Bengaluru", "https://zerodha.com/careers/",
       summary="Bootstrapped discount broker; famously small, high-leverage engineering team.",
       focus="swe,backend", stack="Go,Python,PostgreSQL"),
    _c("Zepto", "product", "tier1", "Bengaluru, Mumbai", "https://www.zeptonow.com/careers",
       summary="10-minute grocery delivery; one of the fastest-scaling Indian startups.",
       aliases=("Kiranakart Technologies",), focus="swe,backend,data", stack="Java,Node.js,Kafka"),
    _c("Navi", "product", "tier2", "Bengaluru", "https://navi.com/careers",
       summary="Lending, insurance and mutual funds; founded by Sachin Bansal.",
       aliases=("Navi Technologies",), focus="swe,backend", stack="Java,Kotlin"),
    _c("Dream11", "product", "tier1", "Mumbai, Bengaluru", "https://www.dreamsports.group/careers/",
       summary="Fantasy sports at extreme concurrency — a genuinely hard scale problem.",
       aliases=("Dream Sports",), focus="swe,backend,infra", stack="Scala,Java,Kafka"),
    _c("Games24x7", "product", "tier2", "Bengaluru, Mumbai", "https://www.games24x7.com/careers/",
       summary="Real-money gaming; heavy on data science and low-latency systems.",
       focus="swe,data,backend", stack="Java,Python"),
    _c("Myntra", "product", "tier2", "Bengaluru", "https://careers.myntra.com/",
       summary="Fashion e-commerce, part of Flipkart Group.",
       focus="swe,backend,frontend", stack="Java,React,Kafka"),
    _c("Nykaa", "product", "tier2", "Mumbai, Bengaluru", "https://www.nykaa.com/careers",
       summary="Beauty and fashion retail, online and offline.",
       focus="swe,backend", stack="Java,Node.js"),
    _c("Lenskart", "product", "tier2", "Gurugram, Bengaluru", "https://www.lenskart.com/careers",
       summary="Eyewear retail with heavy in-house tech and manufacturing.",
       focus="swe,fullstack", stack="Java,React"),
    _c("Urban Company", "product", "tier2", "Gurugram", "https://www.urbancompany.com/careers",
       summary="Home services marketplace with a large matching and logistics problem.",
       aliases=("UrbanClap",), focus="swe,backend,data", stack="Java,Node.js"),
    _c("Delhivery", "product", "tier2", "Gurugram, Bengaluru", "https://www.delhivery.com/careers/",
       summary="Logistics and supply chain; routing and network optimisation at scale.",
       focus="swe,data,backend", stack="Python,Java,Go"),
    _c("Ola", "product", "tier2", "Bengaluru", "https://www.olacabs.com/careers",
       summary="Ride-hailing; sibling companies cover EVs and the Krutrim AI stack.",
       aliases=("ANI Technologies", "Ola Cabs"), focus="swe,backend", stack="Java,Go"),
    _c("Rapido", "product", "growth", "Bengaluru", "https://rapido.bike/careers",
       summary="Bike-taxi and auto marketplace; rapid growth against Ola and Uber.",
       focus="swe,backend", stack="Node.js,Java"),
    _c("MakeMyTrip", "product", "tier2", "Gurugram, Bengaluru", "https://careers.makemytrip.com/",
       summary="Online travel agency; search, pricing and inventory systems.",
       focus="swe,backend,data", stack="Java,Scala,React"),
    _c("ShareChat", "product", "tier2", "Bengaluru", "https://sharechat.com/careers",
       summary="Vernacular social media and Moj short video; heavy ML recommendation work.",
       aliases=("Mohalla Tech", "Moj"), focus="ai_ml,swe,data", stack="Go,Python,Kafka"),
    _c("InMobi", "product", "tier2", "Bengaluru", "https://www.inmobi.com/company/careers",
       summary="Mobile advertising exchange; real-time bidding at high QPS.",
       ats=("greenhouse", "inmobi"), focus="swe,data,backend", stack="Java,Scala,Spark"),
    _c("Glance", "product", "tier2", "Bengaluru", "https://www.glance.com/careers",
       summary="Lock-screen content platform, part of InMobi Group.",
       ats=("greenhouse", "glance"), focus="swe,ai_ml,mobile", stack="Java,Kotlin,Python"),
    _c("Freshworks", "product", "tier2", "Chennai, Bengaluru", "https://www.freshworks.com/company/careers/",
       summary="SaaS CRM and service desk; Chennai-founded, NASDAQ-listed.",
       focus="swe,fullstack", stack="Ruby,Java,React"),
    _c("Zoho", "product", "tier2", "Chennai, Tenkasi", "https://careers.zoho.com/",
       summary="Bootstrapped SaaS suite; famously trains engineers through Zoho Schools.",
       focus="swe,fullstack", stack="Java,JavaScript"),
    _c("Chargebee", "product", "tier2", "Chennai, Bengaluru", "https://www.chargebee.com/careers/",
       summary="Subscription billing and revenue management.",
       focus="swe,backend", stack="Java,React"),
    _c("Postman", "product", "tier1", "Bengaluru, Hyderabad", "https://www.postman.com/company/careers/",
       summary="API development platform used by most working engineers.",
       ats=("greenhouse", "postman"), focus="swe,fullstack,backend", stack="Node.js,React,Go"),
    _c("BrowserStack", "product", "tier1", "Mumbai, Bengaluru", "https://www.browserstack.com/careers",
       summary="Cross-browser testing cloud; large device and VM fleet.",
       focus="swe,infra,backend", stack="Ruby,Go,Kubernetes"),
    _c("Hasura", "startup", "growth", "Bengaluru", "https://hasura.io/careers/",
       summary="Instant GraphQL over databases; strong systems engineering culture.",
       focus="swe,backend", stack="Haskell,Go,TypeScript"),
    _c("Atlan", "startup", "growth", "Bengaluru, Remote", "https://atlan.com/careers/",
       summary="Data catalogue and governance; remote-first Indian company.",
       ats=("ashby", "atlan"), focus="swe,data,fullstack", stack="Java,Python,React"),
    _c("Juspay", "product", "tier2", "Bengaluru", "https://juspay.io/careers",
       summary="Payments orchestration behind much of India's UPI and checkout volume.",
       focus="swe,backend", stack="Haskell,PureScript,Erlang"),
    _c("Cashfree Payments", "product", "tier2", "Bengaluru", "https://www.cashfree.com/careers/",
       summary="Payment gateway and payouts.", aliases=("Cashfree",),
       focus="swe,backend", stack="Java,Node.js"),
    _c("Pine Labs", "product", "tier2", "Noida, Bengaluru", "https://www.pinelabs.com/careers",
       summary="Merchant payments, POS terminals and Setu's API banking stack.",
       aliases=("Setu",), focus="swe,backend", stack="Java,Go"),
    _c("Zeta", "product", "tier2", "Bengaluru, Hyderabad", "https://www.zeta.tech/careers/",
       summary="Modern core banking and card-issuing stack for banks.",
       ats=("lever", "zeta"), focus="swe,backend,infra", stack="Java,Kubernetes"),
    _c("Fi Money", "startup", "growth", "Bengaluru", "https://fi.money/careers",
       summary="Neobank for salaried professionals.", aliases=("Epifi", "Epifi Technologies"),
       ats=("lever", "epifi"), focus="swe,backend,mobile", stack="Go,Kotlin"),
    _c("Fampay", "startup", "growth", "Bengaluru", "https://fampay.in/careers",
       summary="Teen-focused payments and cards.", aliases=("Trio",),
       ats=("lever", "fampay"), focus="swe,backend,mobile", stack="Python,Kotlin"),
    _c("Innovaccer", "product", "tier2", "Noida, Bengaluru", "https://innovaccer.com/careers",
       summary="Healthcare data platform for US providers.",
       focus="swe,data,ai_ml", stack="Python,Go,React"),
    _c("Whatfix", "product", "tier2", "Bengaluru", "https://whatfix.com/careers/",
       summary="Digital adoption platform; in-app guidance overlays.",
       focus="swe,fullstack", stack="Java,JavaScript"),
    _c("Darwinbox", "product", "tier2", "Hyderabad, Bengaluru", "https://darwinbox.com/careers",
       summary="HR tech suite used across Asian enterprises.",
       focus="swe,fullstack", stack="PHP,Node.js,React"),
    _c("MoEngage", "product", "tier2", "Bengaluru", "https://www.moengage.com/careers/",
       summary="Customer engagement and marketing automation.",
       focus="swe,backend,data", stack="Python,Java,Kafka"),
    _c("CleverTap", "product", "tier2", "Mumbai, Bengaluru", "https://clevertap.com/careers/",
       summary="Retention and analytics platform; custom time-series datastore.",
       focus="swe,backend,data", stack="Java,Kafka"),
    _c("Mindtickle", "product", "tier2", "Pune, Bengaluru", "https://www.mindtickle.com/careers/",
       summary="Sales readiness and enablement SaaS.",
       ats=("lever", "mindtickle"), focus="swe,fullstack,data", stack="Java,Python,React"),
    _c("Yellow.ai", "product", "growth", "Bengaluru", "https://yellow.ai/careers/",
       summary="Conversational AI agents for enterprise support.",
       focus="ai_ml,swe,backend", stack="Node.js,Python"),
    _c("Observe.AI", "startup", "growth", "Bengaluru", "https://www.observe.ai/careers",
       summary="Contact-centre speech AI and agent coaching.",
       ats=("greenhouse", "observeai"), focus="ai_ml,swe,data", stack="Python,Go"),
    _c("Uniphore", "product", "tier2", "Chennai, Bengaluru", "https://www.uniphore.com/careers/",
       summary="Conversational automation and voice AI.",
       focus="ai_ml,swe", stack="Python,Java"),
    _c("Sarvam AI", "startup", "growth", "Bengaluru", "https://www.sarvam.ai/careers",
       summary="Indian-language foundation models; a flagship of the India AI mission.",
       ats=("ashby", "sarvam"), focus="ai_ml,swe,infra", stack="Python,PyTorch,CUDA"),
    _c("Krutrim", "startup", "growth", "Bengaluru", "https://www.olakrutrim.com/careers",
       summary="Ola's AI arm — Indic LLMs and an in-house silicon effort.",
       focus="ai_ml,swe,infra", stack="Python,PyTorch"),
    _c("Nurix AI", "startup", "early", "Bengaluru", "https://www.nurix.ai/careers",
       summary="AI agents for customer-facing enterprise workflows.",
       ats=("greenhouse", "nurix"), focus="ai_ml,swe", stack="Python,TypeScript"),
    _c("Composio", "startup", "early", "Bengaluru, San Francisco", "https://composio.dev/careers",
       summary="Tool-calling and integration infrastructure for AI agents.",
       ats=("ashby", "composio"), focus="ai_ml,swe,backend", stack="Python,TypeScript"),
    _c("Fractal Analytics", "product", "tier2", "Mumbai, Bengaluru, Gurugram",
       "https://fractal.ai/careers/", summary="AI and analytics services for Fortune 500 clients.",
       aliases=("Fractal",), focus="ai_ml,data", stack="Python,Spark"),
    _c("Tiger Analytics", "product", "tier2", "Chennai, Bengaluru, Hyderabad",
       "https://www.tigeranalytics.com/careers/", summary="Advanced analytics and data science consulting.",
       focus="ai_ml,data", stack="Python,Spark,AWS"),
    _c("Quantiphi", "product", "tier2", "Mumbai, Bengaluru", "https://quantiphi.com/careers/",
       summary="Applied AI consulting; large Google Cloud partner.",
       focus="ai_ml,data", stack="Python,GCP"),
    _c("Sigmoid", "product", "growth", "Bengaluru", "https://www.sigmoid.com/careers/",
       summary="Data engineering and ML for enterprise clients.",
       ats=("greenhouse", "sigmoid"), focus="data,ai_ml", stack="Python,Spark,Airflow"),
    _c("Hevo Data", "startup", "growth", "Bengaluru", "https://hevodata.com/careers/",
       summary="No-code data pipeline platform.",
       ats=("lever", "hevodata"), focus="swe,data,backend", stack="Java,Kafka"),
    _c("Netradyne", "product", "growth", "Bengaluru", "https://www.netradyne.com/careers",
       summary="Fleet-safety computer vision on edge devices.",
       ats=("greenhouse", "netradyne"), focus="ai_ml,swe", stack="C++,Python,PyTorch"),
    _c("Tekion", "product", "tier2", "Bengaluru, Chennai", "https://tekion.com/careers",
       summary="Cloud-native automotive retail platform.",
       ats=("greenhouse", "tekion"), focus="swe,fullstack", stack="Java,React,AWS"),
    _c("SpotDraft", "startup", "growth", "Bengaluru", "https://www.spotdraft.com/careers",
       summary="Contract lifecycle management with AI extraction.",
       ats=("ashby", "spotdraft"), focus="swe,ai_ml,fullstack", stack="Python,React"),
    _c("Sprinto", "startup", "growth", "Bengaluru, Remote", "https://sprinto.com/careers/",
       summary="Security compliance automation (SOC 2, ISO).",
       focus="swe,fullstack", stack="Node.js,React"),
    _c("Zluri", "startup", "growth", "Bengaluru", "https://www.zluri.com/careers",
       summary="SaaS management and identity governance.",
       focus="swe,fullstack", stack="Node.js,React"),
    _c("Rocketlane", "startup", "growth", "Chennai", "https://www.rocketlane.com/careers",
       summary="Customer onboarding and professional services automation.",
       focus="swe,fullstack", stack="Java,React"),
    _c("Everstage", "startup", "growth", "Chennai", "https://www.everstage.com/careers",
       summary="Sales commission automation.", focus="swe,fullstack", stack="Python,React"),
    _c("Porter", "product", "growth", "Bengaluru", "https://porter.in/careers",
       summary="Intracity logistics marketplace for trucks and two-wheelers.",
       aliases=("Smartshift Logistics",), focus="swe,backend,data", stack="Scala,Java"),
    _c("Zetwerk", "product", "tier2", "Bengaluru", "https://www.zetwerk.com/careers/",
       summary="Manufacturing marketplace for custom industrial parts.",
       focus="swe,backend", stack="Node.js,React"),
    _c("Physics Wallah", "product", "tier2", "Noida, Bengaluru", "https://careers.pw.live/",
       summary="Low-cost exam prep; one of the few profitable Indian edtechs.",
       aliases=("PW",), focus="swe,fullstack", stack="Node.js,React"),
    _c("Unacademy", "product", "growth", "Bengaluru", "https://unacademy.com/careers",
       summary="Online learning and test prep.", focus="swe,fullstack", stack="Python,React"),
    _c("upGrad", "product", "growth", "Mumbai, Bengaluru", "https://www.upgrad.com/careers/",
       summary="Higher education and professional upskilling.",
       focus="swe,fullstack", stack="Java,React"),
    _c("Practo", "product", "growth", "Bengaluru", "https://www.practo.com/careers",
       summary="Healthcare discovery, teleconsult and clinic software.",
       focus="swe,fullstack", stack="Java,Python"),
    _c("HealthifyMe", "product", "growth", "Bengaluru", "https://www.healthifyme.com/careers/",
       summary="Nutrition and fitness coaching with an AI coach.",
       focus="swe,ai_ml,mobile", stack="Python,Kotlin"),
    _c("Licious", "product", "growth", "Bengaluru", "https://www.licious.in/careers",
       summary="Direct-to-consumer meat and seafood with an owned cold chain.",
       focus="swe,backend", stack="Java,Node.js"),
    _c("Cure.fit", "product", "growth", "Bengaluru", "https://www.cult.fit/careers",
       summary="Fitness centres, at-home workouts and nutrition.",
       aliases=("Cult.fit",), focus="swe,fullstack", stack="Java,React"),
    _c("Udaan", "product", "tier2", "Bengaluru", "https://udaan.com/careers",
       summary="B2B commerce for small retailers; large logistics and credit stack.",
       focus="swe,backend,data", stack="Clojure,Java,Kafka"),
    _c("Media.net", "product", "tier2", "Mumbai, Bengaluru", "https://www.media.net/careers/",
       summary="Contextual advertising technology; high-volume ad serving.",
       focus="swe,backend", stack="Java,C++"),
    _c("Amagi", "product", "tier2", "Bengaluru", "https://www.amagi.com/about/careers",
       summary="Cloud broadcast and FAST channel infrastructure.",
       focus="swe,infra,backend", stack="Go,Python,AWS"),
    _c("Hotstar", "product", "tier1", "Bengaluru, Mumbai", "https://careers.jiostar.com/",
       summary="Streaming at record concurrency during live cricket — a famous scale story.",
       aliases=("JioHotstar", "Disney+ Hotstar", "JioStar"),
       focus="swe,infra,backend", stack="Go,Java,Kafka"),

    # ----------------------------------------------------------------------
    # Bengaluru startups (added 2026-10-05). The ATS tokens were checked
    # against each live board: the Greenhouse board name, the Ashby/Lever page
    # title, or the company's own careers page linking to the board. Plausible
    # tokens that were somebody else: `clear` (a US company), `leap` (a US
    # benefits firm), `kiwi` (Latin America). The rest point careers_url at the
    # job board itself (Keka, Darwinbox, Zoho Recruit, Kula, Workable) rather
    # than the marketing page, since that is what scrape.py can read.
    # ----------------------------------------------------------------------
    _c("Ema", "startup", "growth", "Bengaluru, San Francisco", "https://www.ema.co/careers",
       summary="Agentic AI 'employees' for enterprise workflows.",
       aliases=("Ema Unlimited",), ats=("ashby", "ema"), focus="ai_ml,swe",
       stack="Python,TypeScript"),
    _c("TrueFoundry", "startup", "growth", "Bengaluru", "https://www.truefoundry.com/careers",
       summary="Platform for deploying ML models and LLM apps on Kubernetes.",
       ats=("greenhouse", "truefoundry"), focus="ai_ml,infra,swe", stack="Python,Go,Kubernetes"),
    _c("Smallest.ai", "startup", "early", "Bengaluru", "https://smallest.ai/careers",
       summary="Low-latency speech models for real-time voice agents.",
       aliases=("Smallest",), ats=("ashby", "smallest"), focus="ai_ml,swe,infra",
       stack="Python,PyTorch"),
    _c("Bolna", "startup", "early", "Bengaluru", "https://www.bolna.ai/careers",
       summary="Orchestration for voice AI agents, aimed at Indian enterprises.",
       aliases=("Bolna AI",), ats=("ashby", "bolna"), focus="ai_ml,swe,backend",
       stack="Python"),
    _c("Nanonets", "startup", "growth", "Bengaluru, San Francisco", "https://nanonets.com/careers",
       summary="AI document extraction and workflow automation.",
       ats=("ashby", "nanonets"), focus="ai_ml,swe", stack="Python"),
    _c("Bureau", "startup", "growth", "Bengaluru, Mumbai", "https://bureau.id/careers",
       summary="Identity, device and fraud-risk signals for banks and fintechs.",
       aliases=("Bureau ID",), ats=("ashby", "bureau"), focus="swe,backend,data",
       stack="Go,Python"),
    _c("Pocket FM", "startup", "growth", "Bengaluru", "https://www.pocketfm.com/careers",
       summary="Serialised audio-series platform, large in India and the US.",
       aliases=("Pocket Entertainment",), ats=("lever", "pocketfm"),
       focus="swe,data,ai_ml", stack="Java,Python"),
    _c("Nium", "product", "growth", "Bengaluru, Mumbai", "https://www.nium.com/careers",
       summary="Cross-border payments and card-issuing infrastructure.",
       ats=("lever", "nium"), focus="swe,backend", stack="Java,AWS", hq="Singapore"),
    _c("Glean", "product", "tier1", "Bengaluru", "https://www.glean.com/careers",
       summary="Enterprise AI search and assistant over a company's own data.",
       ats=("greenhouse", "gleanwork"), focus="swe,ai_ml,infra", stack="Go,Python,Java",
       hq="Palo Alto"),
    _c("Jupiter", "startup", "growth", "Bengaluru", "https://jupiter.keka.com/careers/",
       summary="Neobank app on top of partner banks: accounts, cards, UPI.",
       aliases=("Jupiter Money", "Amica Financial"), focus="swe,backend", stack="Java,Kotlin"),
    _c("Plum", "startup", "growth", "Bengaluru", "https://careers.kula.ai/plumhq",
       summary="Group health insurance and benefits for employers.",
       aliases=("Plum Benefits",), focus="swe,fullstack", stack="Node.js,React"),
    _c("Increff", "startup", "growth", "Bengaluru", "https://increff.zohorecruit.com/careers",
       summary="Inventory and merchandising SaaS for fashion and retail brands.",
       focus="swe,data", stack="Java,Python"),
    _c("Locus", "startup", "growth", "Bengaluru", "https://locus.darwinbox.in/ms/candidate/careers",
       summary="Route optimisation and dispatch for logistics fleets.",
       aliases=("Locus.sh",), focus="swe,backend,ai_ml", stack="Java,Python"),
    _c("Zuddl", "startup", "growth", "Bengaluru", "https://zuddl.keka.com/careers/",
       summary="Event and webinar platform for B2B marketing teams.",
       focus="swe,fullstack", stack="TypeScript,React,Java"),
    _c("Ninjacart", "startup", "growth", "Bengaluru",
       "https://ninjacart.darwinbox.in/ms/candidatev2/main/careers/home",
       summary="Fresh-produce supply chain from farms to retailers.",
       focus="swe,backend,data", stack="Java"),
    _c("Perfios", "startup", "growth", "Bengaluru", "https://perfios.darwinbox.in/ms/candidate/careers",
       summary="Financial-data analytics and underwriting for lenders.",
       focus="swe,backend,data", stack="Java,Python"),
    _c("Pixxel", "startup", "growth", "Bengaluru", "https://pixxel.darwinbox.in/ms/candidate/careers",
       summary="Hyperspectral earth-imaging satellites and the analytics on top.",
       focus="swe,data,ai_ml", stack="Python,C++"),
    _c("Signzy", "startup", "growth", "Bengaluru", "https://signzy.keka.com/careers/",
       summary="Digital KYC and onboarding APIs for financial institutions.",
       focus="swe,backend,ai_ml", stack="Node.js,Python"),
    _c("Lyzr", "startup", "early", "Bengaluru", "https://careers.lyzr.ai/",
       summary="Framework and platform for enterprise AI agents.",
       aliases=("Lyzr AI",), focus="ai_ml,swe", stack="Python"),
    _c("Apna", "startup", "growth", "Bengaluru, Mumbai", "https://apply.workable.com/apna/",
       summary="Jobs and hiring platform for India's frontline workforce.",
       aliases=("apna.co",), focus="swe,backend,data", stack="Python,React"),
    _c("slice", "startup", "growth", "Bengaluru", "https://slice.bank.in/careers",
       summary="Credit-card fintech that became a small finance bank.",
       aliases=("slice small finance bank",), focus="swe,backend", stack="Java,Kotlin"),
    _c("Khatabook", "startup", "growth", "Bengaluru", "https://khatabook.com/hiring/",
       summary="Bookkeeping and payments apps for small merchants.",
       focus="swe,backend", stack="Go,Kotlin"),
    _c("Scaler", "startup", "growth", "Bengaluru", "https://www.scaler.com/careers/",
       summary="Upskilling programmes for software engineers; also InterviewBit.",
       aliases=("InterviewBit",), focus="swe,fullstack", stack="Ruby,React"),
    _c("Acko", "startup", "growth", "Bengaluru", "https://www.acko.com/careers/",
       summary="Digital-first general insurance: auto, health, travel.",
       focus="swe,backend,data", stack="Java,Python"),
    _c("Kuku FM", "startup", "growth", "Bengaluru", "https://kuku.app/careers/",
       summary="Audio books and series in Indian languages.",
       focus="swe,data", stack="Python,Kotlin"),
    _c("Rupeek", "startup", "growth", "Bengaluru", "https://rupeek.com/careers",
       summary="Doorstep gold-backed loans.", focus="swe,backend", stack="Java,Node.js"),
    _c("Dodo Payments", "startup", "early", "Bengaluru", "https://jobs.pyjamahr.com/dodo-payments",
       summary="Merchant-of-record payments for software and digital products.",
       focus="swe,backend", stack="Rust,TypeScript"),
    _c("Vahan", "startup", "growth", "Bengaluru", "https://vahan.co/careers",
       summary="AI recruiting for blue-collar and gig hiring.",
       aliases=("Vahan.ai",), focus="ai_ml,swe", stack="Python"),
    _c("Digantara", "startup", "growth", "Bengaluru", "https://www.digantara.co.in/careers",
       summary="Space situational awareness: tracking objects in orbit.",
       focus="swe,data", stack="Python,C++"),
    _c("HyperVerge", "startup", "growth", "Bengaluru", "https://hyperverge.co/careers/",
       summary="Face and document AI for identity verification.",
       focus="ai_ml,swe", stack="Python,Node.js"),
    _c("Emergent", "startup", "early", "Bengaluru, San Francisco", "https://emergent.sh/careers",
       summary="Agentic coding platform that builds full apps from a prompt.",
       aliases=("Emergent Labs",), focus="ai_ml,swe,fullstack", stack="Python,TypeScript"),
    _c("Gnani.ai", "startup", "growth", "Bengaluru", "https://www.gnani.ai/careers",
       summary="Voice AI and speech models for Indian languages.",
       aliases=("Gnani",), focus="ai_ml,swe", stack="Python,PyTorch"),

    # ----------------------------------------------------------------------
    # Quant and trading — small teams, very high bar, strong India presence.
    # ----------------------------------------------------------------------
    _c("Tower Research Capital", "product", "tier1", "Gurugram, Mumbai",
       "https://www.tower-research.com/open-positions/",
       summary="High-frequency trading; Gurugram is a major engineering site.",
       ats=("greenhouse", "towerresearchcapital"), focus="quant,swe,infra", stack="C++,Python"),
    _c("Jane Street", "product", "tier1", "Remote", "https://www.janestreet.com/join-jane-street/open-roles/",
       summary="Quantitative trading; hires Indian graduates into Hong Kong and London.",
       ats=("greenhouse", "janestreet"), focus="quant,swe", stack="OCaml"),
    _c("IMC Trading", "product", "tier1", "Mumbai", "https://careers.imc.com/",
       summary="Market maker with a Mumbai technology and trading office.",
       ats=("greenhouse", "imc"), focus="quant,swe", stack="C++,Python"),
    _c("Graviton Research Capital", "product", "tier1", "Gurugram",
       "https://www.gravitontrading.com/careers.html",
       summary="Indian HFT firm; one of the highest-paying entry-level engineering offers.",
       ats=("greenhouse", "gravitonresearchcapital"), focus="quant,swe", stack="C++,Python"),
    _c("WorldQuant", "product", "tier1", "Mumbai, Bengaluru", "https://www.worldquant.com/career-listing/",
       summary="Quantitative asset management and alpha research.",
       ats=("greenhouse", "worldquant"), focus="quant,data", stack="C++,Python"),
    _c("Squarepoint Capital", "product", "tier1", "Mumbai, Bengaluru",
       "https://www.squarepoint-capital.com/careers",
       summary="Systematic trading with growing India engineering.",
       ats=("greenhouse", "squarepointcapital"), focus="quant,swe", stack="C++,Python"),
    _c("Optiver", "product", "tier1", "Mumbai", "https://optiver.com/working-at-optiver/career-opportunities/",
       summary="Market maker; opened a Mumbai office recently.",
       focus="quant,swe", stack="C++,Python"),
    _c("Quadeye", "product", "tier1", "Gurugram", "https://www.quadeye.com/careers",
       summary="Indian quantitative trading firm.", focus="quant,swe", stack="C++,Python"),
    _c("AlphaGrep", "product", "tier1", "Mumbai, Bengaluru", "https://www.alpha-grep.com/careers",
       summary="Quantitative trading across global markets.", focus="quant,swe", stack="C++,Python"),
    _c("D. E. Shaw India", "product", "tier1", "Hyderabad, Gurugram",
       "https://www.deshawindia.com/careers",
       summary="Systematic investing; Hyderabad centre does real research engineering.",
       aliases=("DE Shaw",), focus="quant,swe,data", stack="C++,Python"),
    _c("Arcesium", "product", "tier1", "Hyderabad, Bengaluru", "https://www.arcesium.com/careers",
       summary="Post-trade financial technology spun out of D. E. Shaw.",
       focus="swe,data,backend", stack="Java,Python"),

    # ----------------------------------------------------------------------
    # Services and consulting — the widest funnel, lowest bar, useful as a
    # baseline rather than a target.
    # ----------------------------------------------------------------------
    _c("TCS", "service", "tier2", "Pan-India", "https://www.tcs.com/careers",
       summary="India's largest IT services firm.", aliases=("Tata Consultancy Services",),
       focus="swe"),
    _c("Infosys", "service", "tier2", "Pan-India", "https://www.infosys.com/careers/",
       summary="IT services and consulting; large fresher intake.", focus="swe"),
    _c("Wipro", "service", "tier2", "Pan-India", "https://careers.wipro.com/", summary="IT services.",
       focus="swe"),
    _c("HCLTech", "service", "tier2", "Noida, Chennai, Bengaluru", "https://www.hcltech.com/careers",
       summary="IT and engineering R&D services.", aliases=("HCL",), focus="swe"),
    _c("Tech Mahindra", "service", "tier2", "Pune, Hyderabad", "https://careers.techmahindra.com/",
       summary="IT services with a telecom focus.", focus="swe"),
    _c("LTIMindtree", "service", "tier2", "Mumbai, Bengaluru", "https://www.ltimindtree.com/careers/",
       summary="IT services formed by the L&T Infotech and Mindtree merger.", focus="swe"),
    _c("Mphasis", "service", "tier2", "Bengaluru, Pune", "https://careers.mphasis.com/",
       summary="Applied technology services; cloud and cognitive focus.", focus="swe,ai_ml"),
    _c("Cognizant", "service", "tier2", "Chennai, Pune, Hyderabad", "https://careers.cognizant.com/global/en",
       summary="IT services and consulting.", focus="swe"),
    _c("Accenture", "service", "tier2", "Pan-India", "https://www.accenture.com/in-en/careers",
       summary="Consulting and technology delivery.", focus="swe,data"),
    _c("Capgemini", "service", "tier2", "Pune, Bengaluru, Mumbai", "https://www.capgemini.com/careers/",
       summary="Consulting and engineering services.", focus="swe"),
    _c("Persistent Systems", "service", "tier2", "Pune, Nagpur, Hyderabad",
       "https://www.persistent.com/careers/", summary="Product engineering services.",
       focus="swe,data"),
    _c("Thoughtworks", "service", "tier1", "Bengaluru, Pune, Chennai, Gurugram",
       "https://www.thoughtworks.com/careers",
       summary="Consultancy with an unusually strong engineering-craft culture.",
       ats=("greenhouse", "thoughtworks"), focus="swe,fullstack", stack="Java,Python,React"),
    _c("Nagarro", "service", "tier2", "Gurugram, Pune", "https://www.nagarro.com/en/careers",
       summary="Digital product engineering services.", focus="swe"),
    _c("ZS Associates", "service", "tier1", "Pune, Bengaluru, Gurugram", "https://www.zs.com/careers",
       summary="Consulting with a large data science and engineering practice.",
       focus="data,ai_ml,swe"),
]
